# Generated by Django 3.2.12 on 2022-05-02 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('value_of_information_webapp', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='persistedquery',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
			preserve_default=False,
		),
	]
