# Generated by Django 3.2.12 on 2023-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value_of_information_webapp', '0003_auto_20220509_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistedquery',
            name='raw_form_data_json',
            field=models.CharField(max_length=10000),
        ),
    ]
